# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/goyavewifi/setup-makefiles.sh

PROPRIETARY_FILES := \
    bin/engpc \
    lib/libatparser.so \
    bin/gpsd \
    lib/libsprd_agps_agent.so \
    lib/hw/gps.default.so \
    lib/libboost.so \
    lib/egl/libGLES_mali.so \
    lib/libfactoryutil.so \
    lib/libomission_avoidance.so \
    lib/libatchannel.so \
    vendor/firmware/vbc_eq \
    vendor/firmware/BCM43430A1_001.002.009.0013.0017_ORC_Goya_VE_37_4MHz.hcd \
    lib/libisp.so \
    lib/libmorpho_easy_hdr.so \
    lib/libuvdenoise.so \
    lib/libsecnativefeature.so \
    lib/libomx_aacdec_sprd.so \
    lib/libomx_mp3dec_sprd.so \
    lib/libomx_avcdec_hw_sprd.so \
    lib/libomx_avcenc_hw_sprd.so \
    lib/libomx_vpxdec_hw_sprd.so \
    lib/libomx_m4vh263dec_hw_sprd.so \
    lib/libomx_m4vh263enc_hw_sprd.so \
    lib/hw/gralloc.sc8830.so \
    lib/hw/hwcomposer.sc8830.so \
    lib/hw/sensors.sc8830.so \
    lib/hw/sprd_gsp.sc8830.so

PRODUCT_COPY_FILES += \
    $(foreach f,$(PROPRIETARY_FILES),vendor/samsung/goyavewifi/proprietary/$(f):system/$(f))
