# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/goyavewifi/setup-makefiles.sh

PROPRIETARY_FILES := \
    vendor/bin/engpc \
    vendor/lib/libatparser.so \
    vendor/bin/gpsd \
    vendor/lib/libsprd_agps_agent.so \
    vendor/lib/hw/gps.default.so \
    vendor/lib/libboost.so \
    vendor/lib/egl/libGLES_mali.so \
    vendor/lib/libfactoryutil.so \
    vendor/lib/libomission_avoidance.so \
    vendor/firmware/vbc_eq \
    vendor/etc/wifi/bcmdhd_apsta.bin \
    vendor/etc/wifi/bcmdhd_mfg.bin \
    vendor/etc/wifi/bcmdhd_sta.bin \
    vendor/etc/wifi/nvram_net.txt \
    vendor/firmware/BCM43430A1_001.002.009.0013.0017_ORC_Goya_VE_37_4MHz.hcd \
    vendor/lib/libisp.so \
    vendor/lib/libmorpho_easy_hdr.so \
    vendor/lib/libuvdenoise.so \
    vendor/lib/libsecnativefeature.so \
    vendor/lib/libomx_aacdec_sprd.so \
    vendor/lib/libomx_mp3dec_sprd.so \
    vendor/lib/libomx_avcdec_hw_sprd.so \
    vendor/lib/libomx_avcdec_sw_sprd.so \
    vendor/lib/libomx_avcenc_hw_sprd.so \
    vendor/lib/libomx_vpxdec_hw_sprd.so \
    vendor/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/lib/sensors.vendor.sc8830.so \
    vendor/lib/libcamsensors.so

PRODUCT_COPY_FILES += \
    $(foreach f,$(PROPRIETARY_FILES),vendor/samsung/goyavewifi/proprietary/$(f):system/$(f))
